version: "3.8"
services:
  app:
    #image: film-database-api
    build: .
    ports:
      - "8080:8080"
    environment:
      db-server: db
  db:
    image: postgres
    environment:
      POSTGRES_DB: film-database-api
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    ports:
      - "5432:5432"